data:
  name: ImageNet-100
  datafolder: /root/rjchen/data/imagenet-100
  img_size: 224
  num_classes: 100
  batch_size: 1024
  num_workers: 8
  aug:
    smoothing: 0.1
    mixup: 0.8
    cutmix: 1.0
    cutmix_minmax: null
    mixup_prob: 1.0
    mixup_switch_prob: 0.5
    mixup_mode: batch
  trans:
    color_jitter: 0.4
    aa: rand-m9-mstd0.5-inc1
    train_interpolation: bicubic
    repeated_aug: false
    no_repeated_aug: true
    reprob: 0.25
    remode: pixel
    recount: 1
    resplit: false

search_space:
  search_embed_dim: [192, 216, 240]
  search_depth: [12, 13, 14]
  search_num_heads: [3, 4]
  search_num_ratio: [3.0, 3.5, 4.0]

model:
  name: VisionTransformer
  embed_dim: 240
  depth: 14
  num_heads: 4
  num_ratio: 4.0
  img_size: 224
  patch_size: 16
  in_chans: 3
  qkv_bias: False
  qk_scale: null
  drop_rate: 0.0
  attn_drop_rate: 0.0
  drop_path_rate: 0.1
  pre_norm: True
  scale: False
  abs_pos : True
  global_pool: True
  relative_position: True
  max_relative_position: 14

optimizer:
  opt: adamw
  lr: 0.0005
  opt_eps: 0.00000001
  opt_betas: null
  clip_grad: null
  momentum: 0.9
  weight_decay: 0.05


scheduler:
  sched: cosine
  epochs: 400
  warmup_epochs: 20
  warmup_lr: 0.000001
  min_lr: 0.00001

  lr_noise: null
  lr_noise_pct: 0.67
  lr_noise_std: 1.0
  lr_power: 1.0
  decay_epochs: 30
  cooldown_epochs: 10
  patience_epochs: 10
  decay_rate: 0.1

train:
  sam: true
  sam_rho: 0.1
  sample: random